### ISSUE TITLE
Explore supporting "fix on save"

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-typescript-tslint-plugin#2]
Fix on save is supported by the existing tslint extension. Investigate supporting this with the new plugin based extension as well

Note that this cannot be implemented at the plugin level since the typescript language service has no concept of file saves

**Comment by dawnmist** [comment]
I've been testing the typescript-tslint-plugin & vscode-typescript-tslint-plugin for the last 3 days, and have reached the point where I am now reverting to the previous tslint plugin.

There are 2 primary reasons for the reversion:
1. The lack of support for "fix on save"/no "apply all tslint fixes now" shortcut action.
2. The information about imports popup (window with mouse cursor below) is randomly slow (varies randomly between 2 seconds and more than 30 seconds), and without that information imports do not get added on Ctrl-space and imports such as redux selectors do not tell you which "version" of the selector is which in the list.
![image](https://user-images.githubusercontent.com/5810277/48816145-1bf8cb80-ed95-11e8-83a6-7dd7579fc3ec.png)

The amount of time involved in working through both those issues has been frustrating, and represents a significantly large amount of the day wasted in comparison to using the old tslint plugin.

I am looking forward to a time when this plugin has matured a bit more so that I can retest/migrate across, but without the fix on save feature or an "apply all tslint fixes" shortcut it breaks the flow of programming too much. Every auto-import (once the window finally appears) results in needing to activate fixes at the top of the file (not where you were working in the file) in order to alphabetize them instead of simply hitting Ctrl-S to save the file and having them fixed automatically. Clicking the lightbulb gives access to "apply all fixes", but it's appearance on the screen suffers from the same random-length delay that the information window popup does before it becomes available to be clicked.
