### ISSUE TITLE
Autofix does not fix superfluous formatting

### ISSUE THREAD

**Issue by douglasg14b** [microsoft/vscode-typescript-tslint-plugin#88]
- tslint Version: 1.0.0 (Extension)
- typescript Version: 3.0.0

The "fix all" option doesn't seem to fix many superfluous formatting issues. Such as:

* `missing whitespace`
* `trailing whitespace`
* `" should be '`
* `comment must start with space`
* `missing semicolon`
* `expected onespace after colon in parameter` 

Is this expected behavior? These seem like they would be automatically correctable? Some of these work inconsistently. Such as leading and trailing whitespace work on function declarations, but seemingly on nothing else.

**Comment by douglasg14b** [comment]
Yep. that would be correct!

**Comment by AdrianPal** [comment]
Same for me...

**Comment by mjbvz** [comment]
I can't repo this using 1.2.0 of this extension and tslint 5.1.6. For example, for the file:

```ts
//comment
const str= 'ab'  
```

Fix all formats it to:

```
// comment
const str = "ab"  
```

The only one that is not fixed is the trailing whitespace on the second line because it overlaps with the missing semicolon and change.

Please share some example code where it does not work

**Comment by egamma** [comment]
This extension has been depreacted
